[window]
padding = { x = 40, y = 40 }

[font]
normal = { family = "CozetteVector", style = "Regular" }
bold = { family = "CozetteVector", style = "Regular" }
size = 10

[cursor.style]
shape = "Beam"


[colors.primary]
background = "#ffffff"
foreground = "#0078d7"

# Normal colors
[colors.normal]
black   = '#0078d7'
red     = '#0078d7'
green   = '#0078d7'
yellow  = '#0078d7'
blue    = '#0078d7'
magenta = '#0078d7'
cyan    = '#0078d7'
white   = '#0078d7'

# Bright colors
[colors.bright]
black   = '#0078d7'
red     = '#0078d7'
green   = '#0078d7'
yellow  = '#0078d7'
blue    = '#0078d7'
magenta = '#0078d7'
cyan    = '#0078d7'
white   = '#0078d7'
